logging:
    level:
        org.hibernate.orm.deprecation: error
        org.grails.plugins.support: debug
spring:
    main:
        allow-bean-definition-overriding: true
        allow-circular-references: true
hibernate:
    show_sql: true
    hbm2ddl:
        auto: create
    dialect:  org.hibernate.dialect.H2Dialect
dataSource:
    dbCreate: create-drop
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./build/boot_dev;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
